"""initial final architecture

Revision ID: 55590888dec3
Revises: 
Create Date: 2026-07-14 15:44:42.073501
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55590888dec3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('effect', sa.String(length=20), nullable=False),
    sa.Column('default_risk_level', sa.String(length=10), nullable=False),
    sa.Column('approval_mode', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_capability_version')
    )
    op.create_index(op.f('ix_capability_versions_name'), 'capability_versions', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('connection_type', sa.String(length=40), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('credential_ref', sa.String(length=500), nullable=True),
    sa.Column('host_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_name'), 'connections', ['name'], unique=False)
    op.create_index(op.f('ix_connections_owner_id'), 'connections', ['owner_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('runtime_type', sa.String(length=60), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('workdir', sa.String(length=500), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('policy_profile', sa.String(length=60), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_environment_name')
    )
    op.create_index(op.f('ix_environments_connection_id'), 'environments', ['connection_id'], unique=False)
    op.create_index(op.f('ix_environments_id'), 'environments', ['id'], unique=False)
    op.create_index(op.f('ix_environments_project_id'), 'environments', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_environment_id'), 'chat_sessions', ['environment_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_project_id'), 'chat_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('collector_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('collector_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_runs_environment_id'), 'collector_runs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_collector_runs_project_id'), 'collector_runs', ['project_id'], unique=False)
    op.create_table('context_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_ref', sa.String(length=1000), nullable=False),
    sa.Column('collector_name', sa.String(length=120), nullable=False),
    sa.Column('collector_version', sa.String(length=40), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_sources_environment_id'), 'context_sources', ['environment_id'], unique=False)
    op.create_index(op.f('ix_context_sources_project_id'), 'context_sources', ['project_id'], unique=False)
    op.create_table('experience_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('applicable_entities', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_ref', sa.String(length=1000), nullable=True),
    sa.Column('trust_status', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_items_environment_id'), 'experience_items', ['environment_id'], unique=False)
    op.create_index(op.f('ix_experience_items_project_id'), 'experience_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_experience_items_title'), 'experience_items', ['title'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=60), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_project_id'), 'chat_messages', ['project_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('experience_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_item_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_item_id'], ['experience_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_chunks_experience_item_id'), 'experience_chunks', ['experience_item_id'], unique=False)
    op.create_index(op.f('ix_experience_chunks_project_id'), 'experience_chunks', ['project_id'], unique=False)
    op.create_table('project_entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('properties_json', sa.JSON(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['context_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'environment_id', 'entity_type', 'canonical_name', name='uq_project_entity')
    )
    op.create_index(op.f('ix_project_entities_canonical_name'), 'project_entities', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_project_entities_entity_type'), 'project_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_project_entities_environment_id'), 'project_entities', ['environment_id'], unique=False)
    op.create_index(op.f('ix_project_entities_project_id'), 'project_entities', ['project_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_message_id', sa.Integer(), nullable=False),
    sa.Column('assistant_message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('current_step', sa.String(length=80), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('model_provider', sa.String(length=80), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_environment_id'), 'agent_runs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_message_id'), 'agent_runs', ['user_message_id'], unique=False)
    op.create_table('evidence_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_claims_message_id'), 'evidence_claims', ['message_id'], unique=False)
    op.create_table('project_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('from_entity_id', sa.String(length=36), nullable=False),
    sa.Column('to_entity_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=60), nullable=False),
    sa.Column('properties_json', sa.JSON(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['from_entity_id'], ['project_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['context_sources.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['project_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_entity_id', 'to_entity_id', 'relation_type', name='uq_project_relationship')
    )
    op.create_index(op.f('ix_project_relationships_environment_id'), 'project_relationships', ['environment_id'], unique=False)
    op.create_index(op.f('ix_project_relationships_from_entity_id'), 'project_relationships', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_project_relationships_project_id'), 'project_relationships', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_relationships_relation_type'), 'project_relationships', ['relation_type'], unique=False)
    op.create_index(op.f('ix_project_relationships_to_entity_id'), 'project_relationships', ['to_entity_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('input_summary_json', sa.JSON(), nullable=False),
    sa.Column('output_summary_json', sa.JSON(), nullable=False),
    sa.Column('model_call_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_agent_step_sequence')
    )
    op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_step_type'), 'agent_steps', ['step_type'], unique=False)
    op.create_table('message_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=40), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_feedback_message_id'), 'message_feedback', ['message_id'], unique=True)
    op.create_index(op.f('ix_message_feedback_project_id'), 'message_feedback', ['project_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_run_id'), 'message_feedback', ['run_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_user_id'), 'message_feedback', ['user_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('capability_name', sa.String(length=120), nullable=False),
    sa.Column('capability_version', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('target_json', sa.JSON(), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('effect', sa.String(length=20), nullable=False),
    sa.Column('action_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_action_hash'), 'actions', ['action_hash'], unique=False)
    op.create_index(op.f('ix_actions_capability_name'), 'actions', ['capability_name'], unique=False)
    op.create_index(op.f('ix_actions_environment_id'), 'actions', ['environment_id'], unique=False)
    op.create_index(op.f('ix_actions_project_id'), 'actions', ['project_id'], unique=False)
    op.create_index(op.f('ix_actions_run_id'), 'actions', ['run_id'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_table('model_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('input_token_count', sa.Integer(), nullable=True),
    sa.Column('output_token_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_calls_run_id'), 'model_calls', ['run_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('action_hash', sa.String(length=64), nullable=False),
    sa.Column('requested_from', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('impact_summary', sa.Text(), nullable=False),
    sa.Column('risk_summary', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_from'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_action_id'), 'approvals', ['action_id'], unique=True)
    op.create_index(op.f('ix_approvals_decision'), 'approvals', ['decision'], unique=False)
    op.create_index(op.f('ix_approvals_requested_from'), 'approvals', ['requested_from'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action_id'), 'audit_events', ['action_id'], unique=False)
    op.create_index(op.f('ix_audit_events_environment_id'), 'audit_events', ['environment_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_events_run_id'), 'audit_events', ['run_id'], unique=False)
    op.execute("""
    CREATE FUNCTION reject_audit_event_mutation() RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'audit_events is append-only';
    END;
    $$ LANGUAGE plpgsql
    """)
    op.execute("""
    CREATE TRIGGER audit_events_append_only
      BEFORE UPDATE OR DELETE ON audit_events
      FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation()
    """)
    op.create_table('policy_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('matched_policies_json', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_action_id'), 'policy_decisions', ['action_id'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('executor_type', sa.String(length=60), nullable=False),
    sa.Column('target_ref', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('stdout_ref', sa.Text(), nullable=True),
    sa.Column('stderr_ref', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_invocations_action_id'), 'tool_invocations', ['action_id'], unique=False)
    op.create_index(op.f('ix_tool_invocations_run_id'), 'tool_invocations', ['run_id'], unique=False)
    op.create_table('runtime_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('invocation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('capability_name', sa.String(length=120), nullable=False),
    sa.Column('target_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fresh_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('raw_output_ref', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('is_truncated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['invocation_id'], ['tool_invocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_evidence_action_id'), 'runtime_evidence', ['action_id'], unique=False)
    op.create_index(op.f('ix_runtime_evidence_capability_name'), 'runtime_evidence', ['capability_name'], unique=False)
    op.create_index(op.f('ix_runtime_evidence_environment_id'), 'runtime_evidence', ['environment_id'], unique=False)
    op.create_index(op.f('ix_runtime_evidence_invocation_id'), 'runtime_evidence', ['invocation_id'], unique=False)
    op.create_index(op.f('ix_runtime_evidence_project_id'), 'runtime_evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_runtime_evidence_run_id'), 'runtime_evidence', ['run_id'], unique=False)
    op.create_table('evidence_claim_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('context_source_id', sa.Integer(), nullable=True),
    sa.Column('experience_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['evidence_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['context_source_id'], ['context_sources.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['runtime_evidence.id'], ),
    sa.ForeignKeyConstraint(['experience_item_id'], ['experience_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'evidence_id', 'context_source_id', 'experience_item_id', name='uq_claim_link')
    )
    op.create_index(op.f('ix_evidence_claim_links_claim_id'), 'evidence_claim_links', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_claim_links_claim_id'), table_name='evidence_claim_links')
    op.drop_table('evidence_claim_links')
    op.drop_index(op.f('ix_runtime_evidence_run_id'), table_name='runtime_evidence')
    op.drop_index(op.f('ix_runtime_evidence_project_id'), table_name='runtime_evidence')
    op.drop_index(op.f('ix_runtime_evidence_invocation_id'), table_name='runtime_evidence')
    op.drop_index(op.f('ix_runtime_evidence_environment_id'), table_name='runtime_evidence')
    op.drop_index(op.f('ix_runtime_evidence_capability_name'), table_name='runtime_evidence')
    op.drop_index(op.f('ix_runtime_evidence_action_id'), table_name='runtime_evidence')
    op.drop_table('runtime_evidence')
    op.drop_index(op.f('ix_tool_invocations_run_id'), table_name='tool_invocations')
    op.drop_index(op.f('ix_tool_invocations_action_id'), table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index(op.f('ix_policy_decisions_action_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_audit_events_run_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_environment_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.execute('DROP FUNCTION IF EXISTS reject_audit_event_mutation()')
    op.drop_index(op.f('ix_approvals_requested_from'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_decision'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_action_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_model_calls_run_id'), table_name='model_calls')
    op.drop_table('model_calls')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_run_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_project_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_environment_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_capability_name'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_hash'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_message_feedback_user_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_run_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_project_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_message_id'), table_name='message_feedback')
    op.drop_table('message_feedback')
    op.drop_index(op.f('ix_agent_steps_step_type'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_project_relationships_to_entity_id'), table_name='project_relationships')
    op.drop_index(op.f('ix_project_relationships_relation_type'), table_name='project_relationships')
    op.drop_index(op.f('ix_project_relationships_project_id'), table_name='project_relationships')
    op.drop_index(op.f('ix_project_relationships_from_entity_id'), table_name='project_relationships')
    op.drop_index(op.f('ix_project_relationships_environment_id'), table_name='project_relationships')
    op.drop_table('project_relationships')
    op.drop_index(op.f('ix_evidence_claims_message_id'), table_name='evidence_claims')
    op.drop_table('evidence_claims')
    op.drop_index(op.f('ix_agent_runs_user_message_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_environment_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_project_entities_project_id'), table_name='project_entities')
    op.drop_index(op.f('ix_project_entities_environment_id'), table_name='project_entities')
    op.drop_index(op.f('ix_project_entities_entity_type'), table_name='project_entities')
    op.drop_index(op.f('ix_project_entities_canonical_name'), table_name='project_entities')
    op.drop_table('project_entities')
    op.drop_index(op.f('ix_experience_chunks_project_id'), table_name='experience_chunks')
    op.drop_index(op.f('ix_experience_chunks_experience_item_id'), table_name='experience_chunks')
    op.drop_table('experience_chunks')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_project_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_experience_items_title'), table_name='experience_items')
    op.drop_index(op.f('ix_experience_items_project_id'), table_name='experience_items')
    op.drop_index(op.f('ix_experience_items_environment_id'), table_name='experience_items')
    op.drop_table('experience_items')
    op.drop_index(op.f('ix_context_sources_project_id'), table_name='context_sources')
    op.drop_index(op.f('ix_context_sources_environment_id'), table_name='context_sources')
    op.drop_table('context_sources')
    op.drop_index(op.f('ix_collector_runs_project_id'), table_name='collector_runs')
    op.drop_index(op.f('ix_collector_runs_environment_id'), table_name='collector_runs')
    op.drop_table('collector_runs')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_project_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_environment_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_environments_project_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_connection_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_connections_owner_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_name'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_capability_versions_name'), table_name='capability_versions')
    op.drop_table('capability_versions')
    # ### end Alembic commands ###
