import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { Activity, BadgeCheck, BookOpenText, ChevronRight, CircleAlert, CircleCheck, CircleHelp, Code2, Edit3, Folder, FolderOpen, LogOut, MessageSquare, MoreHorizontal, PanelLeftClose, PanelLeftOpen, PanelRightClose, PanelRightOpen, Pin, PinOff, Plus, RefreshCw, Send, Settings, StopCircle, ThumbsDown, ThumbsUp, Trash2, UserCircle, XCircle } from "lucide-react";
import { cancelRun, collectContext, createExperience, createProject, createSession, decideApproval, deleteExperience, deleteProject, deleteSession, getRun, listActions, listEntities, listEnvironments, listEvidence, listExperience, listGeneralRuns, listGeneralSessions, listMessages, listProjects, listRuns, listSessions, listSteps, queueMessage, sendFeedback, updateExperience, updateProject, updateSession } from "../api/ops";
import type { Action, AgentRun, AgentStep, Approval, ChatMessage, ChatSession, Entity, Environment, Evidence, ExperienceItem, Project, User } from "../api/types";
import { isRunPollingTerminal, markApprovalDecision, rollbackDescription, shouldApplySessionResult } from "../uiState";

type Tab = "activity" | "experience" | "config";
type Menu = {type:"project"|"session";id:number}|null;

export function WorkspacePage({user,onLogout}:{user:User;onLogout:()=>void|Promise<void>}) {
  const [projects,setProjects]=useState<Project[]>([]), [sessions,setSessions]=useState<ChatSession[]>([]), [messages,setMessages]=useState<ChatMessage[]>([]);
  const [environments,setEnvironments]=useState<Environment[]>([]), [runs,setRuns]=useState<AgentRun[]>([]), [experience,setExperience]=useState<ExperienceItem[]>([]), [entities,setEntities]=useState<Entity[]>([]);
  const [projectId,setProjectId]=useState<number|null>(null), [sessionId,setSessionId]=useState<number|null>(null), [input,setInput]=useState(""), [sending,setSending]=useState(false);
  const [projectsReady,setProjectsReady]=useState(false);
  const [activeRunId,setActiveRunId]=useState<string|null>(null), [cancelling,setCancelling]=useState(false);
  const [tab,setTab]=useState<Tab>("activity"), [leftCollapsed,setLeftCollapsed]=useState(false), [rightCollapsed,setRightCollapsed]=useState(false), [navOpen,setNavOpen]=useState(false), [menu,setMenu]=useState<Menu>(null);
  const [notice,setNotice]=useState<{kind:"success"|"error"|"info";text:string}|null>(null), [approvalBusy,setApprovalBusy]=useState<string|null>(null);
  const endRef=useRef<HTMLDivElement|null>(null), messageRefs=useRef<Record<number,HTMLElement|null>>({}), currentSessionRef=useRef<number|null>(null);
  const project=useMemo(()=>projects.find(x=>x.id===projectId)||null,[projects,projectId]);
  const session=useMemo(()=>sessions.find(x=>x.id===sessionId)||null,[sessions,sessionId]);

  useEffect(()=>{void refreshProjects();},[]);
  useEffect(()=>{if(!projectsReady)return;setMessages([]);if(projectId===null){setEnvironments([]);setExperience([]);setEntities([]);Promise.all([listGeneralSessions(),listGeneralRuns()]).then(async([s,r])=>{setSessions(s);setRuns(r);if(s[0])setSessionId(s[0].id);else{const made=await createSession(null);setSessions([made]);setSessionId(made.id);}});return;}Promise.all([listSessions(projectId),listEnvironments(projectId),listRuns(projectId),listExperience(projectId),listEntities(projectId)]).then(async([s,e,r,x,n])=>{setSessions(s);setEnvironments(e);setRuns(r);setExperience(x);setEntities(n);if(s[0])setSessionId(s[0].id);else{const made=await createSession(projectId);setSessions([made]);setSessionId(made.id);}});},[projectId,projectsReady]);
  useEffect(()=>{if(!sessionId)return;Promise.all([listMessages(sessionId),projectId===null?listGeneralRuns(sessionId):listRuns(projectId,sessionId)]).then(([m,r])=>{setMessages(m);setRuns(r);});},[sessionId,projectId]);
  useEffect(()=>{currentSessionRef.current=sessionId;},[sessionId]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth",block:"end"});},[messages,sending]);

  async function refreshProjects(){const rows=await listProjects();setProjects(rows);setProjectId(value=>value&&rows.some(x=>x.id===value)?value:rows[0]?.id??null);setProjectsReady(true);}
  function showNotice(kind:"success"|"error"|"info",text:string){setNotice({kind,text});}
  async function refreshSession(targetSessionId:number,targetProjectId:number|null){const [m,r]=await Promise.all([listMessages(targetSessionId),targetProjectId===null?listGeneralRuns(targetSessionId):listRuns(targetProjectId,targetSessionId)]);if(shouldApplySessionResult(currentSessionRef.current,targetSessionId)){setMessages(m);setRuns(r);}}
  async function refreshCurrentSession(){if(!sessionId)return;await refreshSession(sessionId,projectId);}
  async function newProject(){const name=window.prompt("项目名称")?.trim();if(!name)return;try{const row=await createProject({name});setProjects(x=>sortProjects([row,...x]));setProjectId(row.id);showNotice("success","项目已创建");}catch(error){showNotice("error",error instanceof Error?error.message:"创建项目失败");}}
  async function newSession(){try{const row=await createSession(projectId);setSessions(x=>[row,...x]);setSessionId(row.id);setMessages([]);showNotice("success","新对话已创建");}catch(error){showNotice("error",error instanceof Error?error.message:"创建对话失败");}}
  async function waitForRun(runId:string,targetSessionId:number,targetProjectId:number|null){const deadline=Date.now()+5*60*1000;while(Date.now()<deadline){const run=await getRun(runId);await refreshSession(targetSessionId,targetProjectId);if(isRunPollingTerminal(run.status))return run;await new Promise(resolve=>window.setTimeout(resolve,800));}throw new Error("任务仍在后台运行，请稍后查看活动记录");}
  async function submit(e:FormEvent){e.preventDefault();if(!sessionId||!input.trim()||sending)return;const targetSessionId=sessionId,targetProjectId=projectId,content=input.trim(),tempId=Date.now();setInput("");setSending(true);setMessages(x=>[...x,{id:tempId,session_id:targetSessionId,project_id:targetProjectId,role:"user",content,message_type:"text",metadata_json:{}}]);try{const queued=await queueMessage(targetSessionId,content);setActiveRunId(queued.run_summary.id);setMessages(x=>x.map(m=>m.id===tempId?queued.user_message:m));await waitForRun(queued.run_summary.id,targetSessionId,targetProjectId);}catch(error){showNotice("error",error instanceof Error?error.message:"请求失败");await refreshSession(targetSessionId,targetProjectId);}finally{setActiveRunId(null);setCancelling(false);setSending(false);}}
  async function stopRun(){if(!activeRunId||cancelling)return;setCancelling(true);try{await cancelRun(activeRunId);}finally{setCancelling(false);}}
  async function mutateProject(item:Project,action:"rename"|"pin"|"delete"){setMenu(null);if(action==="rename"){const name=window.prompt("重命名项目",item.name)?.trim();if(name){const row=await updateProject(item.id,{name});setProjects(x=>sortProjects(x.map(v=>v.id===row.id?row:v)));}}else if(action==="pin"){const row=await updateProject(item.id,{is_pinned:!item.is_pinned});setProjects(x=>sortProjects(x.map(v=>v.id===row.id?row:v)));}else if(window.confirm(`删除项目“${item.name}”？`)){await deleteProject(item.id);await refreshProjects();}}
  async function mutateSession(item:ChatSession,action:"rename"|"pin"|"delete"){setMenu(null);if(action==="rename"){const title=window.prompt("重命名聊天",item.title)?.trim();if(title){const row=await updateSession(item.id,{title});setSessions(x=>sortSessions(x.map(v=>v.id===row.id?row:v)));}}else if(action==="pin"){const row=await updateSession(item.id,{is_pinned:!item.is_pinned});setSessions(x=>sortSessions(x.map(v=>v.id===row.id?row:v)));}else if(window.confirm(`删除聊天“${item.title}”？`)){await deleteSession(item.id);const next=sessions.filter(v=>v.id!==item.id);setSessions(next);setSessionId(next[0]?.id??null);}}
  async function approve(item:Approval,decision:"approve"|"reject"){if(approvalBusy||!sessionId)return;const targetSessionId=sessionId,targetProjectId=projectId;setApprovalBusy(item.id);showNotice("info",decision==="approve"?"批准已记录，任务正在排队执行":"拒绝已记录，任务正在安全结束");setMessages(rows=>markApprovalDecision(rows,item.id,decision==="approve"?"approved":"rejected"));try{const result=await decideApproval(item,decision);let finalRun=result.run_summary;if(finalRun){setSending(finalRun.status!=="waiting_for_approval");setActiveRunId(finalRun.status!=="waiting_for_approval"?finalRun.id:null);finalRun=await waitForRun(finalRun.id,targetSessionId,targetProjectId);}else await refreshSession(targetSessionId,targetProjectId);if(finalRun?.status==="waiting_for_approval")showNotice("info","这项决定已记录，仍有其他变更等待确认");else showNotice("success",decision==="approve"?"变更流程已完成":"已拒绝，本次变更未执行");}catch(error){showNotice("error",error instanceof Error?error.message:"审批提交失败");await refreshSession(targetSessionId,targetProjectId);}finally{setApprovalBusy(null);setActiveRunId(null);setSending(false);}}

  return <main className={`workspace ${leftCollapsed?"left-collapsed":""} ${rightCollapsed?"right-collapsed":""}`} onClick={()=>setMenu(null)}>
    {notice&&<div className={`notice ${notice.kind}`}><span>{notice.text}</span><button onClick={e=>{e.stopPropagation();setNotice(null);}}>×</button></div>}
    {leftCollapsed&&<button className="collapsed-open left-open" onClick={()=>setLeftCollapsed(false)} title="打开左侧栏"><PanelLeftOpen size={18}/></button>}
    {rightCollapsed&&<button className="collapsed-open right-open" onClick={()=>setRightCollapsed(false)} title="打开右侧栏"><PanelRightOpen size={18}/></button>}
    <aside className="glass-panel left-pane">
      <button className="pane-toggle" onClick={()=>setLeftCollapsed(true)} title="关闭左侧栏"><PanelLeftClose size={17}/></button>
      <div className="workspace-brand"><div className="brand-chip"><span>&gt;_</span></div><strong>Ops Agent Chat</strong></div>
      <button className="new-chat-primary" onClick={newSession}><Plus size={17}/>新增对话</button>
      <section className={`left-block project-block ${projects.length>3?"compact":""}`}><div className="block-title"><span>项目</span><button className="mini-create" onClick={newProject} title="新建项目"><Plus size={15}/>新建</button></div><div className="project-scroll">
        <div className={`nav-row ${projectId===null?"selected":""}`}><button className="project-item" onClick={()=>setProjectId(null)}><MessageSquare size={19}/><span>通用聊天</span></button></div>
        {projects.map(item=><div className="nav-entry" key={item.id}><div className={`nav-row ${item.id===projectId?"selected":""}`}><button className="project-item" onClick={()=>setProjectId(item.id)} title={item.name}>{item.id===projectId?<FolderOpen size={19}/>:<Folder size={19}/>}<span>{item.name}</span>{item.is_pinned&&<Pin size={13}/>}</button><MoreButton onClick={()=>setMenu(menu?.type==="project"&&menu.id===item.id?null:{type:"project",id:item.id})}/></div>{menu?.type==="project"&&menu.id===item.id&&<ActionMenu pinned={item.is_pinned} onAction={a=>mutateProject(item,a)}/>}</div>)}
      </div></section>
      <section className="left-block session-block"><div className="block-title"><span>聊天记录</span><button className="mini-create" onClick={newSession} title="新建聊天"><Plus size={15}/>新聊天</button></div><div className="session-scroll">
        {sessions.map(item=><div className="nav-entry" key={item.id}><div className={`nav-row ${item.id===sessionId?"selected":""}`}><button className="session-item" onClick={()=>setSessionId(item.id)} title={item.title}><MessageSquare size={16}/><span>{item.title}</span>{item.is_pinned&&<Pin size={13}/>}</button><MoreButton onClick={()=>setMenu(menu?.type==="session"&&menu.id===item.id?null:{type:"session",id:item.id})}/></div>{menu?.type==="session"&&menu.id===item.id&&<ActionMenu pinned={item.is_pinned} onAction={a=>mutateSession(item,a)}/>}</div>)}
      </div></section>
      <button className="logout" onClick={onLogout}><UserCircle size={25}/><span>{user.username}</span><LogOut size={17}/></button>
    </aside>
    <section className="glass-panel chat-pane"><header className="chat-header"><div><strong>{project?.name??"通用聊天"}</strong><span>{session?.title??"新会话"}</span></div><div className="chat-header-actions"><button className={`outline-toggle ${navOpen?"active":""}`} onClick={()=>setNavOpen(x=>!x)} title="消息导航"><MessageSquare size={17}/></button><span className="mode-badge">受控运维</span></div></header>
      <MessageNav open={navOpen} messages={messages} jump={id=>messageRefs.current[id]?.scrollIntoView({behavior:"smooth",block:"center"})}/>
      <div className="message-list">{messages.length===0&&!sending&&<div className="empty-chat"><div className="empty-mark">&gt;_</div><h2>我能帮你处理什么？</h2><p>可以问通用问题，也可以调查当前项目或提出受控变更。</p></div>}
        {messages.map(m=><MessageView key={m.id} message={m} setRef={el=>{messageRefs.current[m.id]=el;}} onApproval={approve} approvalBusy={approvalBusy}/>) }{sending&&<div className="message assistant"><div className="avatar bot-avatar"><Code2 size={18}/></div><div className="assistant-card"><div className="typing-line"><span/><span/><span/></div></div></div>}<div ref={endRef}/></div>
      <form className="composer" onSubmit={submit}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="输入问题或描述要完成的任务" disabled={sending}/>{activeRunId?<button type="button" className="stop-run" onClick={stopRun} disabled={cancelling}><StopCircle size={18}/>{cancelling?"停止中":"停止"}</button>:<button disabled={sending}><Send size={18}/>发送</button>}</form>
    </section>
    <aside className="glass-panel right-pane"><button className="pane-toggle" onClick={()=>setRightCollapsed(true)} title="关闭右侧栏"><PanelRightClose size={17}/></button><div className="right-pane-head"><div className="tabs"><button className={tab==="activity"?"active":""} onClick={()=>setTab("activity")}><Activity size={16}/>活动</button><button className={tab==="experience"?"active":""} onClick={()=>setTab("experience")}><BookOpenText size={16}/>经验</button><button className={tab==="config"?"active":""} onClick={()=>setTab("config")}><Settings size={16}/>配置</button></div></div>
      {tab==="activity"&&<ActivityPanel runs={runs}/>} {tab==="experience"&&(projectId?<ExperiencePanel items={experience} projectId={projectId} onChange={setExperience}/>:<div className="side-card"><p className="empty-note">通用聊天不使用项目经验。</p></div>)} {tab==="config"&&<ConfigPanel project={project} environments={environments} entities={entities} onCollect={async()=>{if(environments[0]){await collectContext(environments[0].id);setEntities(await listEntities(projectId!));}}}/>}
    </aside>
  </main>;
}

function MoreButton({onClick}:{onClick:()=>void}){return <button className="row-menu-trigger" onClick={e=>{e.stopPropagation();onClick();}} title="更多"><MoreHorizontal size={17}/></button>}
function ActionMenu({pinned,onAction}:{pinned:boolean;onAction:(a:"rename"|"pin"|"delete")=>void}){return <div className="action-menu" onClick={e=>e.stopPropagation()}><button onClick={()=>onAction("rename")}><Edit3 size={16}/>重命名</button><button onClick={()=>onAction("pin")}>{pinned?<PinOff size={16}/>:<Pin size={16}/>} {pinned?"取消置顶":"置顶"}</button><button className="danger" onClick={()=>onAction("delete")}><Trash2 size={16}/>删除</button></div>}

function MessageView({message,setRef,onApproval,approvalBusy}:{message:ChatMessage;setRef:(e:HTMLElement|null)=>void;onApproval:(a:Approval,d:"approve"|"reject")=>void;approvalBusy:string|null}){
  if(message.role==="user")return <article className="message user" ref={setRef}><div className="user-bubble">{message.content}</div></article>;
  const approvals=message.metadata_json.approvals||[];
  return <article className="message assistant" ref={setRef}><div className="avatar bot-avatar"><Code2 size={18}/></div><div className="assistant-card"><div className="answer-header"><span>Ops Agent</span><small>{String(message.metadata_json.run_status||"")}</small></div><RichText text={message.content}/>{approvals.map(a=><ApprovalCard key={a.id} item={a} busy={approvalBusy===a.id} onDecision={d=>onApproval(a,d)}/>)}{Boolean(message.metadata_json.evidence_ids?.length)&&<div className="source-strip"><span>依据</span><em>{message.metadata_json.evidence_ids!.length} 条可追踪证据</em></div>}<Feedback messageId={message.id}/></div></article>;
}
function RichText({text}:{text:string}){return <div className="natural-answer">{text.split(/\n{2,}/).map((p,i)=>{const lines=p.split("\n");return <div key={i} className="answer-paragraph">{lines.map((line,j)=>{const value=line.replace(/^#{1,6}\s*/,"");if(/^#{1,6}\s/.test(line))return <h4 key={j}>{formatInline(value)}</h4>;if(/^[-*]\s+/.test(line))return <p className="answer-bullet" key={j}>{formatInline(value.replace(/^[-*]\s+/,""))}</p>;if(/^\d+\.\s+/.test(line))return <p className="answer-number" key={j}>{formatInline(line)}</p>;return <p key={j}>{formatInline(value)}</p>})}</div>})}</div>}
function formatInline(text:string){return text.split(/(`[^`]+`|\*\*[^*]+\*\*)/g).filter(Boolean).map((part,i)=>part.startsWith("`")&&part.endsWith("`")?<code key={i}>{part.slice(1,-1)}</code>:part.startsWith("**")&&part.endsWith("**")?<strong key={i}>{part.slice(2,-2)}</strong>:part)}
function ApprovalCard({item,busy,onDecision}:{item:Approval;busy:boolean;onDecision:(d:"approve"|"reject")=>void}){const pending=item.decision==="pending";const view=approvalView(item);return <section className="approval-card"><div className="approval-title"><CircleCheck size={18}/><strong>{pending?"需要你确认":"审批已处理"}</strong><span className={`approval-state ${item.decision}`}>{approvalStateText(item.decision,busy)}</span></div><div className="approval-main"><h4>{view.title}</h4><p>{view.impact}</p><p>{view.risk}</p></div><details className="approval-technical"><summary>查看技术细节</summary><p><b>能力</b><code>{item.action?.capability_name||"未知"}</code></p><p><b>目标</b><code>{view.target}</code></p><p><b>前置检查</b><span>{humanCapability(item.action?.precheck)||"无"}</span></p><p><b>执行验证</b><span>{humanCapability(item.action?.verifier)||"无"}</span></p><p><b>异常恢复</b><span>{rollbackDescription(item.action)}</span></p><small>有效期至 {new Date(item.expires_at).toLocaleString()}</small></details>{pending&&<div className="approval-actions"><button disabled={busy} onClick={()=>onDecision("reject")}><XCircle size={16}/>{busy?"提交中":"拒绝"}</button><button disabled={busy} className="approve" onClick={()=>onDecision("approve")}><CircleCheck size={16}/>{busy?"执行中":"批准"}</button></div>}</section>}
function approvalView(item:Approval){const capability=item.action?.capability_name||"";const target=String(item.action?.target_json?.name||item.action?.arguments_json?.service||"当前目标");const verb=capabilityVerb(capability);return {title:`确认${verb}${target}`,impact:naturalImpact(item,verb,target),risk:naturalRisk(item,verb,target),target};}
function capabilityVerb(value:string){return ({"service.restart":"重启服务 ","service.start":"启动服务 ","service.stop":"停止服务 ","service.scale":"调整服务副本 ","config.update":"修改配置 "} as Record<string,string>)[value]||"执行变更 ";}
function humanCapability(value?:string|null){return value?({"service.status":"检查服务状态","service.logs":"查看服务日志","service.restart":"重启服务","service.start":"启动服务","service.stop":"停止服务","service.scale":"调整服务副本","config.update":"修改配置"} as Record<string,string>)[value]||value:"";}
function naturalImpact(item:Approval,verb:string,target:string){if(item.impact_summary&&!/[a-z]+\.[a-z]+|\{.*\}/i.test(item.impact_summary))return item.impact_summary;return `Agent 准备${verb}${target}。批准后会执行这次变更，并在执行后再次检查服务状态。`;}
function naturalRisk(item:Approval,verb:string,target:string){if(item.risk_summary&&!/[a-z]+\.[a-z]+|requires explicit approval|rollback/i.test(item.risk_summary))return item.risk_summary;const action=verb.trim();return `${action}可能让 ${target} 短暂不可用，正在处理的请求可能中断。当前没有自动回滚步骤，如果执行后状态异常，需要继续人工确认或再次让 Agent 诊断。`;}
function approvalStateText(decision:string,busy:boolean){if(busy)return "处理中";if(decision==="approved")return "已批准";if(decision==="rejected")return "已拒绝";if(decision==="expired")return "已过期";return "待确认";}
function Feedback({messageId}:{messageId:number}){const [done,setDone]=useState("");async function rate(r:string){await sendFeedback(messageId,r);setDone(r)}return <div className="feedback-row"><span>{done?"已记录":"评价回答"}</span>{!done&&<><button onClick={()=>rate("helpful")} title="有帮助"><ThumbsUp size={15}/></button><button onClick={()=>rate("incomplete")} title="不完整"><ThumbsDown size={15}/></button><button onClick={()=>rate("inaccurate")} title="不准确"><CircleAlert size={15}/></button><button onClick={()=>rate("unresolved")} title="未解决"><CircleHelp size={15}/></button></>}</div>}
function MessageNav({open,messages,jump}:{open:boolean;messages:ChatMessage[];jump:(id:number)=>void}){return <aside className={`message-outline ${open?"open":""}`}><h3>消息导航</h3>{messages.map(m=><button key={m.id} className={`message-nav-row ${m.role}`} onClick={()=>jump(m.id)}><span>{m.role==="user"?"你":"Agent"}</span><strong>{m.content.replace(/[#*`]/g,"").slice(0,48)}</strong></button>)}</aside>}

function ActivityPanel({runs}:{runs:AgentRun[]}){
  const [selected,setSelected]=useState<string|null>(null), [steps,setSteps]=useState<AgentStep[]>([]), [actions,setActions]=useState<Action[]>([]), [evidence,setEvidence]=useState<Evidence[]>([]);
  const [loading,setLoading]=useState(false), [loadError,setLoadError]=useState("");
  async function expand(id:string){
    if(selected===id){setSelected(null);return;}
    setSelected(id);setSteps([]);setActions([]);setEvidence([]);setLoadError("");setLoading(true);
    try{const [s,a,e]=await Promise.all([listSteps(id),listActions(id),listEvidence(id)]);setSteps(s);setActions(a);setEvidence(e);}
    catch(error){setLoadError(error instanceof Error?error.message:"活动详情加载失败");}
    finally{setLoading(false);}
  }
  return <div className="side-card"><h3>Agent 活动</h3>{runs.length===0&&<p className="empty-note">当前会话暂无活动。</p>}{runs.map(run=><div className={`activity-row ${selected===run.id?"expanded":""}`} key={run.id}><button onClick={()=>expand(run.id)} aria-expanded={selected===run.id}><StatusDot status={run.status}/><span><strong>{goalOf(run)}</strong><small>{run.current_step||run.status} · {run.step_count} 步</small></span><ChevronRight className="activity-chevron" size={16}/></button>{selected===run.id&&<div className="activity-detail">{loading&&<p className="activity-note">正在加载活动详情...</p>}{loadError&&<p className="activity-error">{loadError}</p>}{!loading&&!loadError&&<>{run.status==="failed"&&<p className="activity-error">运行失败：{run.error_code||"未知错误"}</p>}<div className="step-list">{steps.map(step=><p key={step.id}><b>{step.sequence}. {stepLabel(step.step_type)}</b><span className={step.status}>{step.status==="success"?"完成":"失败"}</span></p>)}</div>{actions.map(a=><p key={a.id}><code>{a.capability_name}</code><span>{a.status}</span></p>)}{evidence.map(e=><details key={e.id} className="evidence-detail"><summary><b>{e.summary}</b><small>{new Date(e.observed_at).toLocaleTimeString()}</small></summary><pre>{JSON.stringify(e.data_json,null,2)}</pre><em>{e.fresh_until?`有效至 ${new Date(e.fresh_until).toLocaleTimeString()}`:"静态上下文"}</em></details>)}{actions.length===0&&evidence.length===0&&<p className="activity-note">本次请求未产生工具调用或运行证据。</p>}</>}</div>}</div>)}</div>;
}
function StatusDot({status}:{status:string}){return <i className={`status-dot ${status}`}/>}function goalOf(run:AgentRun){return String(run.request_json?.summary||run.request_json?.goal||"Agent 请求")}
function stepLabel(value:string){return ({resolve_capabilities:"解析可用能力",decision:"模型决策",policy:"策略检查",execute:"工具执行",await_approval:"等待审批",finish:"生成结果"} as Record<string,string>)[value]||value;}
function ExperiencePanel({items,projectId,onChange}:{items:ExperienceItem[];projectId:number;onChange:(x:ExperienceItem[])=>void}){const [saving,setSaving]=useState(false);async function upload(file?:File){if(!file)return;setSaving(true);try{const content=await file.text();const row=await createExperience(projectId,{title:file.name,content,trust_status:"draft",tags:["uploaded"]});onChange([row,...items]);}finally{setSaving(false)}}async function verify(item:ExperienceItem){const row=await updateExperience(item.id,{trust_status:"verified"});onChange(items.map(x=>x.id===row.id?row:x))}async function remove(item:ExperienceItem){if(!window.confirm(`删除经验“${item.title}”？`))return;await deleteExperience(item.id);onChange(items.filter(x=>x.id!==item.id))}return <div className="side-card"><h3>项目经验</h3><label className="upload-line"><input type="file" accept=".md,.txt" onChange={e=>upload(e.target.files?.[0])}/><span>{saving?"保存中":"添加文档"}</span></label>{items.map(x=><div className="doc-row" key={x.id}><span><strong>{x.title}</strong><small>{x.trust_status==="verified"?"已验证":"草稿"} · {x.item_type}</small></span><div>{x.trust_status!=="verified"&&<button className="icon-action" onClick={()=>verify(x)} title="标记为已验证"><BadgeCheck size={15}/></button>}<button className="icon-action" onClick={()=>remove(x)} title="删除经验"><Trash2 size={15}/></button></div></div>)}</div>}
function ConfigPanel({project,environments,entities,onCollect}:{project:Project|null;environments:Environment[];entities:Entity[];onCollect:()=>void}){const env=environments[0];if(!project)return <div className="side-card"><p className="empty-note">请选择项目。</p></div>;return <div className="side-card config-list"><div className="config-heading"><h3>项目配置</h3><button className="icon-action" onClick={onCollect} title="采集上下文"><RefreshCw size={16}/></button></div><p><span>项目</span><strong>{project.name}</strong></p><p><span>环境</span><strong>{env?.name||"未配置"}</strong></p><p><span>运行时</span><strong>{env?.runtime_type||"未配置"}</strong></p><p><span>工作目录</span><strong>{env?.workdir||"未配置"}</strong></p><p><span>策略</span><strong>{env?.policy_profile||"未配置"}</strong></p><p><span>连接</span><strong>{env?.connection_id?"已引用":"未配置"}</strong></p><p><span>上下文实体</span><strong>{entities.length}</strong></p></div>}
function sortProjects(rows:Project[]){return [...rows].sort((a,b)=>Number(b.is_pinned)-Number(a.is_pinned)||a.name.localeCompare(b.name))}function sortSessions(rows:ChatSession[]){return [...rows].sort((a,b)=>Number(b.is_pinned)-Number(a.is_pinned)||(b.updated_at||"").localeCompare(a.updated_at||""))}
